services:
  web:
    image: example/hibernate-example
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8001:8001"
    depends_on:
      - db
  db:
    image: example/postgres:latest
    build:
      dockerfile: db/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres